name = "token_shoken"
version = "1.0.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = "~> 0.52"
wisp = "~> 1.5"
gleam_http = "~> 3.7"
mist = "~> 4.0"
gjwt = "~> 1.0"
gleam_json = "~> 2.3"
gleam_erlang = "~> 0.33"
dot_env = "~> 1.2"
cake = ">= 2.1.0 and < 3.0.0"
cake_sqlight = ">= 1.1.1 and < 2.0.0"
sqlight = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
